### PR TITLE
add aliases handling to licenses-plugin

### PR DESCRIPTION
**Pull request by michpetrov**

### CODE REVIEW

**Comment by michpetrov** [comment]
@bstansberry could I get this reviewed? Thanks.

**Comment by jamezp** [comment]
@emmartins Could you review this?

**Comment by emmartins** [comment]
@jamezp I never worked with the licenses plugin

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @michpetrov!

**Pull request merged**
